# Generated by Django 5.1.6 on 2025-02-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='isbn',
        ),
    ]
